package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CoverPhotoAlbum generated by hbm2java
 */
@Entity
@Table(name="cover_photo_album"
    ,catalog="socialsite"
)
public class CoverPhotoAlbum  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="cover_photo_id", unique=true, nullable=false)
     private Long coverPhotoId;
     @Column(name = "user_id", nullable = false)
     private Integer userId;
     @Column(name = "added_date", nullable = false)
     private Date addedDate;
     @Column(name="file_link", nullable=false, length=45)
     private String fileLink;

    public CoverPhotoAlbum() {
    }

    public CoverPhotoAlbum(Integer userId, Date addedDate, String fileLink) {
        this.userId = userId;
        this.addedDate = addedDate;
        this.fileLink = fileLink;
    }

    public Long getCoverPhotoId() {
        return coverPhotoId;
    }

    public void setCoverPhotoId(Long coverPhotoId) {
        this.coverPhotoId = coverPhotoId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Date getAddedDate() {
        return addedDate;
    }

    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    public String getFileLink() {
        return fileLink;
    }

    public void setFileLink(String fileLink) {
        this.fileLink = fileLink;
    }

    

}


