package com.social.entity;
// Generated Apr 24, 2017 9:29:38 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PostLikes generated by hbm2java
 */
@Entity
@Table(name="post_likes"
    ,catalog="socialsite"
)
public class PostLikes  implements java.io.Serializable {

     @Id @GeneratedValue(strategy=IDENTITY)
     @Column(name="post_likes_id", unique=true, nullable=false)
     private Integer postLikesId;
     @Column(name = "post_id", nullable = false)
     private Integer postId;
     @Column(name = "user_id", nullable = false)
     private Integer userId;
     @Column(name="status", nullable=false)
     private int status;

    public PostLikes() {
    }

    public PostLikes(Integer postLikesId, Integer postId, Integer userId, int status) {
        this.postLikesId = postLikesId;
        this.postId = postId;
        this.userId = userId;
        this.status = status;
    }
    

    public PostLikes(Integer postId, Integer userId, int status) {
        this.postId = postId;
        this.userId = userId;
        this.status = status;
    }

    public Integer getPostLikesId() {
        return postLikesId;
    }

    public void setPostLikesId(Integer postLikesId) {
        this.postLikesId = postLikesId;
    }

    public Integer getPostId() {
        return postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    
    

}


